### ISSUE TITLE
Two-column theme?

### ISSUE THREAD

**Issue by dginev** [dginev/ar5iv-css#1]
It is uncanny how close we get to the the 2-column view in some class PDF files simply by adding:
```css
.ltx_abstract,
.ltx_section,
.ltx_appendix,
.ltx_bibliography {
  columns: 2;
}
```

To the CSS ruleset. Adding that as a toggle-able theme, orthogonal to the light/dark theme toggle, feels rather reasonable as an experiment.

But every type of content that refuses to reflow, makes this difficult. Cases I've spotted on a quick glance:
 - long display equations, and their tags
 - certain side-margin notes get stuck between columns
 - verbatim code blocks sized for a single-column width
 - tables sized for a single-column width

So maybe it is best to defer this until we can auto-reflow nearly everything, and see if there is additional interest / ideas floating around.
