### ISSUE TITLE
Custom selection highlights?

### ISSUE THREAD

**Issue by dginev** [dginev/ar5iv-css#2]
I stumbled on a blog that had enabled custom selection highlights which seemed nice. For ar5iv, they would be roughly equivalent to:

```css
:root {
  --background_contrast_pop: rgba(157, 157, 171, 0.4);
}

[data-theme="dark"] .ltx_document ::selection, .ltx_document ::-moz-selection {
  background-color: var(--background_contrast_pop, #724714);
}
[data-theme="light"] .ltx_document ::selection, .ltx_document ::-moz-selection {
  background-color: var(--background_contrast_pop, #8db8eb);
}
```

Some early testing comments:
 - The MathML support is a bit inconsistent in Firefox, it looks like `<mo>` elements are not covered?
 - The Firefox selections seem to encounter some lag with the custom rule - especially on a large document. Is that annoying to lay users?
 - Also if desired, what are the most reasonable colors?

Shelving it as an issue for now, but if anyone wants to take over and experiment - feel free and let me know.
